[package]
name = "coreos-stream-metadata"
version = "0.1.0"
authors = ["Colin Walters <walters@verbum.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
nix = ">= 0.20, < 0.24"
serde = { version = "^1.0", features = ["derive"] }
strum = ">= 0.20, < 0.23"
strum_macros = ">= 0.20, < 0.23"

[dev-dependencies]
anyhow = "1.0"
serde_json = "1.0"
